---
  - name: Install Apache
    apt:
      name: apache2
      state: present

  - name: Configure Apache
    template:
      src: apache.conf.j2
      dest: /etc/apache2/apache.conf
      owner: admin
      group: admin
      mode: '0644'
    notify: Restart Apache