---
  - name: Baseline Configuration
    hosts: all
    user: admin
    become: true  # This replaces user: root, to run tasks as root
    roles: 
      - role: base 

  - name: Apache
    hosts: apache
    user: admin
    become: true  # This replaces user: root, to run tasks as root
    roles: 
      - role: apache 


  # - name: Postgresql
  #   hosts: postgresql
  #   user: admin
  #   become: true  # This replaces user: root, to run tasks as root
  #   roles: 
  #     - role: postgres